//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalprj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingInfo()
        {
            this.CustomerInfo = new HashSet<CustomerInfo>();
        }
    
        public int BookingID { get; set; }
        public string Name { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> TotalMembers { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.TimeSpan> BookingTime { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
        public string EmailID { get; set; }
        public string PhoneNumber { get; set; }
        public byte[] FileUpload { get; set; }
        public string Message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInfo> CustomerInfo { get; set; }
    }
}
